apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    operator:
      replicas: 1
      enabled: true
    ui:
      # enable Hubble UI
      enabled: true
      standalone:
        # enable Hubble UI standalone deployment
        enabled: true
