apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 5m
  targetNamespace: kube-system
  install:
    remediation:
      retries: 4
  values:
    operator:
      replicas: 1
  
