apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    operator:
      replicas: 1
    relay:
      create: true
      name: hubble-relay
      automount: false
      annotations: {}
    ui:
      create: true
      name: hubble-ui
      automount: true
      annotations: {}
    hubble:
        # -- Enable Hubble (true by default).
      enabled: true
        # -- Annotations to be added to all top-level hubble objects (resources under templates/hubble)
      annotations: {}
